### PR TITLE
chore: update guile-sys to support Rust 1.10.0

### PR DESCRIPTION
**Pull request by kwrooijen**
Hi @lidavidm 

Added libc as dependency (since it's now part of crates.io).
Removed Cargo.lock from .gitignore, probably shouldn't be there.
The shell example now runs with these changes.

I saw that this package was yanked from crates.io, is there any reason for that? I'd like to use this package for future projects (or at least guile-sys).

### CODE REVIEW

**Comment by lidavidm** [comment]
Hi Kevin! Thanks for the PR, will take a look soon.

I yanked it because I couldn't figure out a good solution to Guile's use of longjmp/setjmp (see issue #1), and I didn't want to mislead people looking for bindings. If you have any ideas there I'd be curious to hear them. Maybe it makes more sense to keep it published, though.

I also don't really maintain this anymore (got busy with other stuff), if possible and if you're interested, I'd be willing to transfer this + the Cargo package to you too.

**Comment by lidavidm** [comment]
I've merged this for now, I can republish it when I get home if you like?

**Comment by kwrooijen** [comment]
I'm not really a system's programmer, and still quite new to Rust. So I doubt I could figure out a solution for that. I won't be needing this library soon. It's not a problem for me to not have it hosted on crates.io at the moment.

I'll continue looking at this library and maybe look into that issue (Although my understanding of it is extremely limited). So possibly in the future I might consider taking it over :)

Thanks for the merge!

**Comment by lidavidm** [comment]
Alright, just let me know :+1:

**Comment by lidavidm** [comment]
Just unyanked and bumped the version, in case you need it on crates.io it's there now.

**Pull request merged**
